### PR TITLE
Added APIM resource

### PR DESCRIPTION
**Pull request by juanpabloguerra16**

### CODE REVIEW

**Comment by seekdavidlee** [comment]
@juanpabloguerra16  - Seems like the last Action is failing still. Assuming you will fix that before I review the PR?

**Comment by juanpabloguerra16** [comment]
@seekdavidlee I was able to finally deploy the APIM inside the VNET. The last action fails because I was trying to add the XML but since the APIM is inside a subnet, there's a Nsg blocking inbound traffic from the GH action workers. I will fix it on Monday most likely and then we can merge to main. Thanks

**Comment by seekdavidlee** [comment]
Sounds good @juanpabloguerra16 ! Will check the PR again when this is completed Monday. Have a great weekend!

**Comment by seekdavidlee** [comment]
@juanpabloguerra16  Just checking, are u still working on this or can I complete the code review and approve the PR?

**Comment by juanpabloguerra16** [comment]
@seekdavidlee I finally was able to deploy =D. I still have more to do but feel free to complete the PR and I can start a new dev locally in case someone else pushes to dev

**Pull request merged**
